### PR TITLE
Some of the issue fixes

### PR DESCRIPTION
**Pull request by djain2405**
https://github.com/Droidcon-Boston/conference-app-android/issues/189 -> 
Now it wont crash but sometimes I am still getting the following FirebaseUiException which doesnt crash the app but shows the alert with the code and the message as follows. I researched and it says its because SHA1 is not added to Firebase.. Anybody can help me with that?
E/AuthUI: A sign-in error occurred.
com.firebase.ui.auth.FirebaseUiException: Code: 10, message: 10: 
    at com.firebase.ui.auth.data.remote.GoogleSignInHandler.onActivityResult(GoogleSignInHandler.java:106)

https://github.com/Droidcon-Boston/conference-app-android/issues/187
https://github.com/Droidcon-Boston/conference-app-android/issues/169
https://github.com/Droidcon-Boston/conference-app-android/issues/167

### CODE REVIEW

**Comment by fetching** [comment]
Hi @djain2405   Chris added my SHA1 to Firebase in https://github.com/Droidcon-Boston/conference-app-android/issues/179 so I could get around the "Code 10, Message 10". If you post it to him he can add you or I can possibly add it later this evening.

**Comment by n8ebel** [comment]
@djain2405   I did some quick testing on this.  When tap the feedback stars, then dismiss the sign in dialog, I'm no longer seeing the crash, but I am still getting the "rate" dialog which the user shouldn't see at that point.

@fetching Do you have time to verify the fixes for the other issues?

**Comment by fetching** [comment]
Yes @n8ebel  I will test fixes

**Comment by fetching** [comment]
@n8ebel I still see this issue but the PR isn't merged yet. I'll test again after merge.

**Comment by n8ebel** [comment]
@djain2405  do you have time to check on the qa finding i listed above?

**Comment by djain2405** [comment]
@n8ebel Merging this PR and will check the dialog one finding tomorrow and submit another PR for the fix!

**Pull request merged**
