### PR TITLE
switch app to use 2019 DB

### PR DESCRIPTION
**Pull request by kenyee**

### CODE REVIEW

**Comment by kenyee** [comment]
That's a pretty lame circleCI error :-P

```
#!/bin/sh -eo pipefail
# No configuration was found in your project. Please refer to https://circleci.com/docs/2.0/ to get started with your configuration.
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
```

**Comment by AdamMc331** [comment]
So this works, which caught me off guard. Is it just because the 2019 link still includes the data that was there for 2018?

**Comment by kenyee** [comment]
Yes, I mentioned it in standup or in the channel a few weeks back.
I exported the 2018 DB and imported it into this new DB....Justin already switched the iOS app to use it.
Still waiting for the real links to the SlidesUp 2019 data so I can work on the auto import script for that....was hoping to use Firebase Functions but they're Javascript only :-P  I'll write up a bit more on what I've dug up in the slack channel.  Trying to make all the scripting/backend changes pretty much transparent to both apps :-)

**Comment by AdamMc331** [comment]
Ah gotcha. Sorry I was out of the loop for a bit. 🙈 Good with me then.

**Comment by CCorrado** [comment]
hey @kenyee, rebase this branch on top of develop and it should pass :)

**Pull request merged**
