### PR TITLE
fix the background color of my schedule 

### PR DESCRIPTION
**Pull request by kenyee**
so it doesn't look like last session in that list is super big

### CODE REVIEW

**Comment by nisrulz** [comment]
@kenyee Didn't quite get the issue it fixes. Could you share a screenshot of the issue you are seeing?

**Comment by kenyee** [comment]
@nisrulz: look at the color underneath the session item for after/before:
screen shot 2018-03-08 at 1 51 09 pm
screen shot 2018-03-08 at 1 49 50 pm

**Comment by kenyee** [comment]
@nisrulz are you sure we're merging to develop?  I thought we didn't have code freeze yet?  I merged the session over indicator into master already :-(

**Comment by nisrulz** [comment]
Wel I dont know about you, but I have been merging to develop since I stated it in slack channel.

**Comment by kenyee** [comment]
ahh..thought this was a bugfix as was the other PR.
New features go into develop for sure (and I do remember you mentioning that in slack).  Was also talking to Jinn at a meetup this week and he didn't think we'd have official code freeze until the end of the week.

**Pull request merged**
